M48
; DRILL file KiCad 10.0.3 date 2026-05-28T20:07:32
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-28T20:07:32+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X112.1Y-88.6
X115.1Y-88.6
T2
X116.685Y-36.0
X121.535Y-36.0
T3
X60.0Y-35.0
X60.0Y-176.0
X116.385Y-32.97
X121.835Y-32.97
X133.5Y-35.0
X133.5Y-176.0
M30
